# Generated by Django 3.0.4 on 2020-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descrp',
            field=models.TextField(default='', max_length=300),
        ),
    ]
