# Generated by Django 3.0.5 on 2020-05-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='top_selling',
            field=models.BooleanField(default=False),
        ),
    ]
